version: '3'

networks:
  openhim:

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    networks:
      - openhim
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim-development"
      mongo_atnaUrl: "mongodb://mongo-db/openhim-development"
      NODE_ENV: "development"
      # api_authenticationTypes: ["token", "basic", "openid", "local"]
      # Edit the following to enable SSO authentication (openid)
      # api_openid_url: ${KC_FRONTEND_URL}/realms/${KC_REALM_NAME}
      # api_openid_callbackUrl: ${KC_OPENHIM_ROOT_URL}
      # api_openid_clientId: ${KC_OPENHIM_CLIENT_ID}
      # api_openid_clientSecret: ${KC_OPENHIM_CLIENT_SECRET}
      OPENHIM_CORE_HTTPS_KEY: "/etc/openhim/tls/private.key"
      OPENHIM_CORE_HTTPS_CERT: "/etc/openhim/tls/certificate.crt"
    # ports:
    #   - "8075:8080"
    #   - "5000:5000"
    #   - "5001:5001"
    networks:
      - openhim
    volumes:
      - "/root/ssl_certs/certificate.key:/etc/openhim/tls/private.key:ro"
      - "/root/ssl_certs/certificate.crt:/etc/openhim/tls/certificate.crt:ro"
    healthcheck:
     test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    networks:
      - openhim
    ports:
      - "9000:80"
    volumes:
      - "./default.json:/usr/share/nginx/html/config/default.json:ro"
      - "/root/ssl_certs/certificate.key:/etc/openhim/tls/private.key:ro"
      - "/root/ssl_certs/certificate.crt:/etc/openhim/tls/certificate.crt:ro"
    healthcheck:
     test: "curl -sS http://openhim-console || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3

volumes:
  mongo-data:
